### ISSUE TITLE
10. As an item, I want my estimated next purchase date to be computed at the time my purchase is recorded in the database so the app can learn how often I buy different items.

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-16-smart-shopping-list#10]
AC:

* When a purchase is recorded, the estimated number of days until the next purchase date should be calculated and recorded in the database

The script at `/src/lib/estimates.js` should be used to calculate the next estimated purchase interval.

**Comment by skylerwshaw** [comment]
Some consideration should be made for data that is needed as inputs to the function in `estimates.js` and the output possibilities and type. We may need to adjust the schema for an item to accommodate the data points required by the function:
https://github.com/the-collab-lab/tcl-16-smart-shopping-list/blob/a92a67751e8e0960fb638b2b853bee6e1fdfd25e/src/lib/estimates.js#L2-L23
